
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/software/cmake-4.1.1-windows-x86_64/cmake-4.1.1-windows-x86_64/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
...
